import json
from datetime import datetime
from unittest.mock import Mock, patch

import pytest

from claude_vault.models import Conversation, Message
from claude_vault.tagging import OfflineTagGenerator


@pytest.fixture
def mock_conversation():
    return Conversation(
        title="Test Conversation",
        messages=[
            Message(role="human", content="Hello world"),
            Message(role="assistant", content="Hi there"),
        ],
        created_at=datetime.now(),
        updated_at=datetime.now(),
    )


@pytest.fixture
def tag_generator():
    with patch("claude_vault.tagging.load_config") as mock_config:
        mock_config.return_value.ollama.url = "http://localhost:11434/api/generate"
        mock_config.return_value.ollama.model = "llama3.2"
        mock_config.return_value.ollama.temperature = 0.7
        mock_config.return_value.ollama.timeout = 30
        mock_config.return_value.custom_keywords = {}
        return OfflineTagGenerator()


def test_generate_metadata_success(tag_generator, mock_conversation):
    """Test successful generation of tags and summary from JSON response"""
    expected_response = {
        "tags": ["python", "testing", "mock"],
        "summary": "This is a test summary generated by AI.",
    }

    mock_response = Mock()
    mock_response.status_code = 200
    mock_response.json.return_value = {"response": json.dumps(expected_response)}

    with patch("requests.post", return_value=mock_response):
        with patch("requests.get", return_value=Mock(status_code=200)):
            result = tag_generator.generate_metadata(mock_conversation)

            assert result["tags"] == ["python", "testing", "mock"]
            assert result["summary"] == "This is a test summary generated by AI."


def test_generate_metadata_invalid_json_fallback(tag_generator, mock_conversation):
    """Test fallback when LLM returns invalid JSON"""
    # LLM returns just comma-separated text instead of JSON
    mock_response = Mock()
    mock_response.status_code = 200
    mock_response.json.return_value = {"response": "python, raw-text, formatting"}

    with patch("requests.post", return_value=mock_response):
        with patch("requests.get", return_value=Mock(status_code=200)):
            result = tag_generator.generate_metadata(mock_conversation)

            assert "python" in result["tags"]
            assert "raw-text" in result["tags"]
            assert result["summary"] is None


def test_generate_metadata_service_unavailable(tag_generator, mock_conversation):
    """Test fallback when Ollama is not running"""
    with patch("requests.get", side_effect=Exception("Connection refused")):
        result = tag_generator.generate_metadata(mock_conversation)

        # Should fall back to keyword extraction (title contains "test")
        assert "testing" in result["tags"]
        assert result["summary"] is None


def test_validate_metadata_cleaning(tag_generator):
    """Test metadata validation and cleaning logic"""
    dirty_input = {
        "tags": [" valid-tag ", "INVALID_TAG!", "too-long-" * 5, "good-tag"],
        "summary": 123,  # Not a string
    }

    result = tag_generator._validate_metadata(dirty_input)

    assert "valid-tag" in result["tags"]
    assert "good-tag" in result["tags"]
    assert "invalid_tag!" not in result["tags"]  # Cleaned out
    assert len(result["tags"]) == 2
    assert result["summary"] == "123"  # Converted to string
