from unittest.mock import patch

import frontmatter
import pytest
from typer.testing import CliRunner

from claude_vault.cli import app
from claude_vault.models import Conversation, Message

runner = CliRunner()


@pytest.fixture
def mock_tag_generator():
    with patch("claude_vault.cli.OfflineTagGenerator") as mock_generator:
        instance = mock_generator.return_value
        instance.is_available.return_value = True
        instance.config.ollama.model = "test-model"
        instance.generate_metadata.return_value = {
            "tags": ["test-tag", "cli-test"],
            "summary": "Generated by CLI test.",
        }
        yield instance


@pytest.fixture
def mock_parser():
    with patch("claude_vault.cli.ClaudeExportParser") as mock_parser:
        instance = mock_parser.return_value
        instance.parse_conversation_from_markdown.return_value = Conversation(
            title="Test Conversation",
            messages=[Message(role="human", content="Test content")],
            created_at="2023-01-01",
            updated_at="2023-01-01",
        )
        yield instance


def test_retag_command(mock_tag_generator, mock_parser, tmp_path):
    """Test that retag command calls generate_metadata and updates file"""
    # Create a dummy markdown file
    conversations_dir = tmp_path / "conversations"
    conversations_dir.mkdir()

    md_file = conversations_dir / "test-conv.md"
    post = frontmatter.Post("Test content", title="Test Conversation", tags=["old-tag"])
    md_file.write_text(frontmatter.dumps(post))

    # Run command
    result = runner.invoke(app, ["retag", "--vault-path", str(tmp_path), "--force"])

    assert result.exit_code == 0
    assert "Updated 1 conversations" in result.stdout
    assert "Generated by CLI test" in result.stdout

    # Verify file content
    updated_post = frontmatter.load(md_file)
    assert "test-tag" in updated_post["tags"]
    assert updated_post["summary"] == "Generated by CLI test."
